# Generated by Django 3.0 on 2021-02-15 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commondata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('header_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('processor', models.TextField(blank=True, null=True)),
                ('RAM', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laptopsdata',
            fields=[
                ('commondata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CRUD_adminapp.commondata')),
                ('HD_capacity', models.TextField(blank=True, null=True)),
            ],
            bases=('CRUD_adminapp.commondata',),
        ),
        migrations.CreateModel(
            name='mobilesdata',
            fields=[
                ('commondata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='CRUD_adminapp.commondata')),
                ('screensize', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
            ],
            bases=('CRUD_adminapp.commondata',),
        ),
    ]
